"""Bug bounty tools for Strix.

Provides tools for:
- Writing HackerOne/Bugcrowd-quality vulnerability reports
- CVSS v3.1 score calculation
- Scope checking and deduplication search
- Fetching disclosed reports for duplicate avoidance
"""

from __future__ import annotations

import json
import logging
import re
import urllib.error
import urllib.request
from datetime import datetime
from typing import Any

try:
    from agents import function_tool, RunContextWrapper
    _HAS_AGENTS = True
except ImportError:
    _HAS_AGENTS = False

logger = logging.getLogger(__name__)

# CVSS v3.1 base score calculation weights
_AV = {"N": 0.85, "A": 0.62, "L": 0.55, "P": 0.2}
_AC = {"L": 0.77, "H": 0.44}
_PR_unchanged = {"N": 0.85, "L": 0.62, "H": 0.27}
_PR_changed = {"N": 0.85, "L": 0.68, "H": 0.5}
_UI = {"N": 0.85, "R": 0.62}
_CIA = {"N": 0.0, "L": 0.22, "H": 0.56}


def _cvss31_score(
    av: str, ac: str, pr: str, ui: str, s: str,
    c: str, i: str, a: str,
) -> tuple[float, str]:
    """Calculate CVSS v3.1 base score and severity label."""
    scope_changed = s.upper() == "C"
    pr_weight = _PR_changed[pr.upper()] if scope_changed else _PR_unchanged[pr.upper()]

    iss = 1 - (1 - _CIA[c.upper()]) * (1 - _CIA[i.upper()]) * (1 - _CIA[a.upper()])
    if scope_changed:
        impact = 7.52 * (iss - 0.029) - 3.25 * pow(iss - 0.02, 15)
    else:
        impact = 6.42 * iss

    exploitability = (
        8.22
        * _AV[av.upper()]
        * _AC[ac.upper()]
        * pr_weight
        * _UI[ui.upper()]
    )

    if impact <= 0:
        base = 0.0
    elif scope_changed:
        base = min(1.08 * (impact + exploitability), 10.0)
    else:
        base = min(impact + exploitability, 10.0)

    base = round(base * 10) / 10  # round to 1 decimal

    if base == 0:
        label = "None"
    elif base < 4.0:
        label = "Low"
    elif base < 7.0:
        label = "Medium"
    elif base < 9.0:
        label = "High"
    else:
        label = "Critical"

    return base, label


def _build_report(
    title: str,
    vuln_type: str,
    endpoint: str,
    summary: str,
    steps: list[str],
    impact: str,
    cvss_vector: str,
    evidence: str = "",
    remediation: str = "",
    references: list[str] | None = None,
    platform: str = "hackerone",
) -> str:
    """Build a formatted bug bounty report in Markdown."""
    # Parse CVSS vector to get score
    score_str = ""
    try:
        parts = dict(p.split(":") for p in cvss_vector.replace("CVSS:3.1/", "").split("/"))
        score, label = _cvss31_score(
            parts["AV"], parts["AC"], parts["PR"], parts["UI"], parts["S"],
            parts["C"], parts["I"], parts["A"],
        )
        score_str = f"**CVSS v3.1 Score:** {score} ({label})\n**Vector:** {cvss_vector}"
    except Exception:
        score_str = f"**CVSS Vector:** {cvss_vector}"

    steps_md = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
    refs_md = ""
    if references:
        refs_md = "\n## References\n" + "\n".join(f"- {r}" for r in references)

    report = f"""# {title}

## Summary

{summary}

## Severity

{score_str}

## Steps to Reproduce

{steps_md}

## Proof of Concept

{evidence or '[Include screenshots, HTTP requests, video, or logs demonstrating the vulnerability]'}

## Impact

{impact}

## Remediation

{remediation or '[Describe the fix — input validation, output encoding, auth check, etc.]'}
{refs_md}

---
*Report generated by Strix on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
"""
    return report.strip()


if _HAS_AGENTS:
    @function_tool
    async def calculate_cvss(
        ctx: RunContextWrapper,
        av: str,
        ac: str,
        pr: str,
        ui: str,
        s: str,
        c: str,
        i: str,
        a: str,
    ) -> str:
        """Calculate CVSS v3.1 base score.

        Args:
            av: Attack Vector — N (Network), A (Adjacent), L (Local), P (Physical)
            ac: Attack Complexity — L (Low), H (High)
            pr: Privileges Required — N (None), L (Low), H (High)
            ui: User Interaction — N (None), R (Required)
            s: Scope — U (Unchanged), C (Changed)
            c: Confidentiality Impact — N (None), L (Low), H (High)
            i: Integrity Impact — N (None), L (Low), H (High)
            a: Availability Impact — N (None), L (Low), H (High)

        Returns JSON with score, severity label, and vector string.
        """
        try:
            score, label = _cvss31_score(av, ac, pr, ui, s, c, i, a)
            vector = f"CVSS:3.1/AV:{av.upper()}/AC:{ac.upper()}/PR:{pr.upper()}/UI:{ui.upper()}/S:{s.upper()}/C:{c.upper()}/I:{i.upper()}/A:{a.upper()}"
            return json.dumps({
                "score": score,
                "severity": label,
                "vector": vector,
                "calculator_url": f"https://www.first.org/cvss/calculator/3.1#{vector}",
            }, indent=2)
        except Exception as e:
            return f"Error calculating CVSS: {e}"

    @function_tool
    async def write_bounty_report(
        ctx: RunContextWrapper,
        title: str,
        vuln_type: str,
        endpoint: str,
        summary: str,
        steps_json: str,
        impact: str,
        cvss_av: str = "N",
        cvss_ac: str = "L",
        cvss_pr: str = "N",
        cvss_ui: str = "N",
        cvss_s: str = "U",
        cvss_c: str = "H",
        cvss_i: str = "H",
        cvss_a: str = "N",
        evidence: str = "",
        remediation: str = "",
        references_json: str = "",
        platform: str = "hackerone",
        output_file: str = "",
    ) -> str:
        """Write a professional bug bounty report in HackerOne/Bugcrowd format.

        Args:
            title: Report title, e.g. "Stored XSS in profile bio allows account takeover"
            vuln_type: Vulnerability type, e.g. "Stored XSS", "SQLi", "SSRF", "IDOR"
            endpoint: Affected endpoint or component, e.g. "/api/profile/update"
            summary: 2-3 sentence description of the vulnerability and impact
            steps_json: JSON array of reproduction steps, e.g. '["Step 1", "Step 2"]'
            impact: Description of business/security impact
            cvss_av: Attack Vector (N/A/L/P)
            cvss_ac: Attack Complexity (L/H)
            cvss_pr: Privileges Required (N/L/H)
            cvss_ui: User Interaction (N/R)
            cvss_s: Scope (U/C)
            cvss_c: Confidentiality (N/L/H)
            cvss_i: Integrity (N/L/H)
            cvss_a: Availability (N/L/H)
            evidence: Proof of concept, HTTP requests, logs
            remediation: Suggested fix
            references_json: JSON array of reference URLs
            platform: Target platform — "hackerone" or "bugcrowd"
            output_file: If set, save report to this file path in /workspace
        """
        try:
            steps = json.loads(steps_json) if steps_json else []
        except json.JSONDecodeError:
            steps = [steps_json]

        try:
            references = json.loads(references_json) if references_json else []
        except json.JSONDecodeError:
            references = []

        vector = f"CVSS:3.1/AV:{cvss_av.upper()}/AC:{cvss_ac.upper()}/PR:{cvss_pr.upper()}/UI:{cvss_ui.upper()}/S:{cvss_s.upper()}/C:{cvss_c.upper()}/I:{cvss_i.upper()}/A:{cvss_a.upper()}"

        report = _build_report(
            title=title,
            vuln_type=vuln_type,
            endpoint=endpoint,
            summary=summary,
            steps=steps,
            impact=impact,
            cvss_vector=vector,
            evidence=evidence,
            remediation=remediation,
            references=references,
            platform=platform,
        )

        if output_file:
            from pathlib import Path
            out = Path(f"/workspace/{output_file}") if not output_file.startswith("/") else Path(output_file)
            out.write_text(report, encoding="utf-8")
            return f"Report saved to {out}\n\n---\n\n{report}"

        return report

    @function_tool
    async def search_disclosed_reports(
        ctx: RunContextWrapper,
        query: str,
        limit: int = 10,
    ) -> str:
        """Search HackerOne disclosed reports to check for duplicates.

        Args:
            query: Search query, e.g. "XSS profile target.com"
            limit: Max results to return (default 10)

        Returns list of disclosed reports matching the query.
        """
        # Use HackerOne Hacktivity public API
        url = f"https://hackerone.com/graphql"
        payload = json.dumps({
            "query": """
            query HacktivityQuery($query: String!, $limit: Int!) {
                search(index: CompleteHacktivityReportIndexDocument, query: $query, first: $limit) {
                    nodes {
                        ... on HacktivityDocument {
                            url id
                            reporter { username }
                            team { handle name }
                            severity_rating
                            report { title disclosed_at }
                        }
                    }
                }
            }
            """,
            "variables": {"query": query, "limit": limit},
        }).encode()

        try:
            req = urllib.request.Request(
                url,
                data=payload,
                headers={
                    "Content-Type": "application/json",
                    "User-Agent": "Strix-Security-Scanner/1.0",
                },
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read())

            nodes = data.get("data", {}).get("search", {}).get("nodes", [])
            if not nodes:
                return f"No disclosed HackerOne reports found for query: {query}"

            results = []
            for node in nodes[:limit]:
                report = node.get("report", {})
                team = node.get("team", {})
                results.append({
                    "title": report.get("title", ""),
                    "program": team.get("handle", ""),
                    "severity": node.get("severity_rating", ""),
                    "disclosed": report.get("disclosed_at", ""),
                    "url": f"https://hackerone.com{node.get('url', '')}",
                })

            return json.dumps(results, indent=2)

        except Exception as e:
            return (
                f"Could not fetch HackerOne reports (may require login): {e}\n"
                f"Search manually at: https://hackerone.com/hacktivity?querystring={urllib.parse.quote(query)}"
            )

    @function_tool
    async def estimate_bounty(
        ctx: RunContextWrapper,
        program: str,
        cvss_score: float,
        vuln_type: str,
    ) -> str:
        """Estimate bug bounty payout based on severity and program type.

        Args:
            program: Program name or tier — "large_tech", "startup", "government", "bank"
            cvss_score: CVSS v3.1 score (0.0-10.0)
            vuln_type: Type of vulnerability found

        Returns estimated bounty range and tips.
        """
        ranges = {
            "large_tech": {   # Google, Apple, Microsoft, Meta
                "critical": (10000, 50000),
                "high":     (5000, 20000),
                "medium":   (1000, 5000),
                "low":      (100, 1000),
            },
            "startup": {
                "critical": (2000, 10000),
                "high":     (500, 3000),
                "medium":   (100, 500),
                "low":      (50, 200),
            },
            "bank": {
                "critical": (5000, 30000),
                "high":     (2000, 10000),
                "medium":   (500, 2000),
                "low":      (100, 500),
            },
            "government": {
                "critical": (1000, 5000),
                "high":     (500, 2000),
                "medium":   (100, 500),
                "low":      (50, 200),
            },
        }

        if cvss_score >= 9.0:
            sev = "critical"
        elif cvss_score >= 7.0:
            sev = "high"
        elif cvss_score >= 4.0:
            sev = "medium"
        else:
            sev = "low"

        prog_ranges = ranges.get(program.lower(), ranges["startup"])
        lo, hi = prog_ranges[sev]

        tips = {
            "critical": "RCE/auth bypass reports often get maximum payout. Include working PoC and clear impact demonstration.",
            "high": "LPE, SSRF-to-internal, SQLi reports. Chain with other issues to increase severity.",
            "medium": "IDOR, stored XSS. Show concrete impact beyond theory.",
            "low": "Open redirect, self-XSS, info disclosure. Often low or N/A without chaining.",
        }

        return json.dumps({
            "estimated_range_usd": f"${lo:,} – ${hi:,}",
            "severity": sev.upper(),
            "cvss_score": cvss_score,
            "vuln_type": vuln_type,
            "program_tier": program,
            "tip": tips[sev],
        }, indent=2)

# Fallback stubs when agents SDK not available
else:
    def calculate_cvss(*a, **kw): raise ImportError("agents SDK not installed")
    def write_bounty_report(*a, **kw): raise ImportError("agents SDK not installed")
    def search_disclosed_reports(*a, **kw): raise ImportError("agents SDK not installed")
    def estimate_bounty(*a, **kw): raise ImportError("agents SDK not installed")

import urllib.parse  # noqa: E402  (import at bottom to avoid circular)
